version: "3"

services:
  # db:
  #   image: postgres:13
  #   volumes:
  #     - ./data/db:/var/lib/postgres/data
  #   environment:
  #     - POSTGRES_DB=postgres
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #   ports:
  #   - 5433:5432

  # backend:
  #   build: ./backend
  #   volumes:
  #     - ./backend:/home/app
  #     - ${CONTENTS_PATH}:/opt/mount
  #   restart: always
  #   command: >
  #     sh -C "python manage.py makemigrations &&
  #     python manage.py migrate &&
  #     gunicorn sample-prj.wsgi -b 0.0.0.0:8000 --reload --workers 4 --timeout=300 --log-level=debug"
  #   environment:
  #     - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
  #   depends_on:
  #     - db

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/home/app
      - /home/app/node_modules
      - /home/app/.next
    restart: always
    command: npm run dev
    ports:
      - 3000:3000
